### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by dimrozakis** [makearl/tornado-profile#15]
Hey there. I've written a simple python script in https://github.com/dimrozakis/tornado-profile-client that interfaces with a tornado server using tornado-profile. It can enable/disable the profiler, as well as fetch/clear stats. It supports all parameters currently exposed for fetching of stats. Results are printed in stdout in tables. The script supports running against multiple tornado servers. Just thought to open this issue to let you know about the script, in case it is of interest to you.

**Comment by grantpatten** [comment]
Thanks! Used this earlier today, this looks great.  Adding a link to the readme now.
